# Generated by Django 5.1.4 on 2024-12-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0004_remove_post_categories_category_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="Posts", to="blogging.category"
            ),
        ),
    ]
